ALTER TABLE criancas ADD COLUMN tipo_gestacao VARCHAR(20) NOT NULL DEFAULT 'NAO_INFORMADO';
ALTER TABLE criancas ADD COLUMN status_t21 VARCHAR(30) NOT NULL DEFAULT 'PREFIRO_INFORMAR_DEPOIS';
ALTER TABLE criancas ADD COLUMN status_turner VARCHAR(30) NOT NULL DEFAULT 'PREFIRO_INFORMAR_DEPOIS';
ALTER TABLE criancas ADD COLUMN outra_condicao_relevante BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE criancas ADD COLUMN observacoes_condicao_relevante VARCHAR(1000);
