package br.com.pueria.pueria.desenvolvimento.dominio;
public interface HistoricoRespostaMarcoDesenvolvimentoRepositorio { HistoricoRespostaMarcoDesenvolvimento salvar(HistoricoRespostaMarcoDesenvolvimento historico); }
